import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  const { data: session, status } = useSession();

  console.log(session);
  

  return (
    <div className="">
      <Head>
        <title>Hyrstacken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto p-8">
        <div className="flex w-full gap-2 items-center">          
            {session ? (
              <>
                <p className="ml-auto">{session.user?.email}</p>
                <button className="btn btn-secondary" onClick={() => signOut()}>Logga Ut</button>
              </>
            ) : (
              <>
                <p className="ml-auto">Ej inloggad</p>
                <button className="btn btn-primary" onClick={() => signIn()}>Logga In</button>
              </>
            )}          
        </div>

      <div>
        <Link href={'/createItem'} className="btn">Ny Annons</Link>
      </div>
        
      </main>

    </div>
  );
}
