name: Check the source code
on:
    pull_request:
        branches:
            - master
jobs:
    test:
        name: Check the source code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install packages
              run: npm ci
            - name: Prettier
              run: npm run format
            - name: Lint
              run: npm run lint
            - uses: cypress-io/github-action@v4.2.0
            - name: Cypress
              with:
                  browser: chrome
                  start: npm run dev && npm run cypress:open
                  wait-on: "http://localhost:3000"
                  wait-on-timeout: 60
